version: "3.7"

services:
  app:
    build: ./docker
    image: simpeg/laravel
    ports:
      - "8080:80"
    volumes:
      # Mount source-code for development
      - ./:/var/www
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: simpeg
      MYSQL_PASSWORD: simpeg

      
  phpmyadmin_1:
    image: phpmyadmin
    ports:
      - 8081:8080
    links:
      - db
    environment:
      - PMA_ARBITARY=1
      - PMA_PORT=3306
      - PMA_HOST=db

volumes:
  mysql-data: